#!/usr/bin/env bash
# Script that configures an Ubuntu server to change localhost and facebook.com IP addresses

# Create a copy of the hosts file
cp /etc/hosts ~/hosts.new

# Update the localhost and facebook.com IP addresses
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the hosts file with the new version
cp -f ~/hosts.new /etc/hosts
