#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine

# Use the ifconfig command and filter out only IPv4 addresses
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6- || ip addr | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-
